---
title: "exercise2_ESM215"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
ex2dat <- read.csv("ex2_sample_data2.csv")

clean_dat2 <- ex2dat %>% 
  filter(landcover != "-9999") %>% 
    filter(geology != "-9999") %>% 
    filter(flowaccum != "-9999") %>% 
    filter(winter_rad != "-9999")



# find our MI
geoi_tidy <- mi.empirical(table(clean_dat2$landcover, clean_dat2$geology))

flowi_tidy <- mi.empirical(table(clean_dat2$landcover, clean_dat2$flowaccum))

rad_tidy <- mi.empirical(table(clean_dat2$landcover, clean_dat2$winter_rad))


# find MI in between variables 
geio1_filtered <- clean_dat2 %>% 
  filter(geology == "1")
geio1_filtered

mi.empirical(table(geio1_filtered$landcover, geio1_filtered$flowaccum))
#0.005231603

mi.empirical(table(geio1_filtered$landcover, geio1_filtered$winter_rad))
#0.03752635



geio2_filtered <- clean_dat2 %>% 
  filter(geology == "2")
geio2_filtered

mi.empirical(table(geio2_filtered$landcover, geio2_filtered$flowaccum))
#0.01049795

mi.empirical(table(geio2_filtered$landcover, geio2_filtered$winter_rad))
#0.05438607



geio3_filtered <- clean_dat2 %>% 
  filter(geology == "3")
geio3_filtered

mi.empirical(table(geio3_filtered$landcover, geio3_filtered$flowaccum))
#0.007399254

mi.empirical(table(geio3_filtered$landcover, geio3_filtered$winter_rad))
#0.05876362








#

table(ex2dat[,5],ex2dat[,6])


dat2 <- ex2dat[ex2dat[,6] != -9999,5:8]

head(dat2)


dim(dat2)
# 9990 4

#Find the Mutual Information Statistic
#geology
geomi <- mi.empirical(table(dat2[,1],dat2[,2]))
#0.2286847

#flow
flowmi <- (table(dat2[,1],dat2[,3]))
# 0.00543883

#radiation
radiationmi <- mi.empirical(table(dat2[,1],dat2[,4]))
# 0.05124749

mi_df <- data.frame("Geology" = 0.2286847, "Flow" = 0.00543883, "Radiation" = 0.05124749)
mi_df

```

Mutual Information Analysis
```{r, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE}
mi_table <- kable




```

```{r}
ls()
# "dat2"      "ex2dat"    "ex2dat_df"


dim(dat2g1)


#this is the highest in geology
#then we break dataset into subsets where each subset is one rock type, geology I, II, III
#we are developing a hierarchy here
#have to do it inside of each rock class
#compare within each geological starta
#once in that rock category, what is the next most associated variable to land cover
#they all recursively partition the data into different subsets
#as we work our way down the tree we want to increase predictive sk
```
Trying to build a tree graph by subdividing the world by certain factors 
g1 and g2 are class geologies
